RestoBundle\Entity\Salade:
    type: entity
    table: null
    repositoryClass: RestoBundle\Repository\SaladeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        description:
            type: string
            length: 255
        prix:
            type: float
    lifecycleCallbacks: {  }
