<?php

namespace RestoBundle\Repository;

/**
 * SaladeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaladeRepository extends \Doctrine\ORM\EntityRepository
{
}
